# Generated by Django 4.2.10 on 2025-11-16 11:28

from django.db import migrations, models
from django.utils.text import slugify


def generate_slugs(apps, schema_editor):
    Event = apps.get_model('events', 'Event')
    for event in Event.objects.all():
        if not event.slug:
            base_slug = slugify(event.title)
            slug = base_slug
            counter = 1
            while Event.objects.filter(slug=slug).exclude(pk=event.pk).exists():
                slug = f"{base_slug}-{counter}"
                counter += 1
            event.slug = slug
            event.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True, max_length=300),
        ),
        migrations.RunPython(generate_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, unique=True),
        ),
    ]
