# Generated by Django 4.2.10 on 2025-11-16 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cover_file',
            field=models.ImageField(blank=True, null=True, upload_to='events/covers/'),
        ),
        migrations.AddField(
            model_name='event',
            name='cover_image',
            field=models.URLField(blank=True),
        ),
    ]
