# Generated by Django 4.2.10 on 2025-11-15 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На модерации'), ('published', 'Опубликовано'), ('rejected', 'Отклонено')], default='draft', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('website', models.URLField(blank=True)),
                ('vk_link', models.URLField(blank=True)),
                ('telegram_link', models.URLField(blank=True)),
                ('logo_url', models.URLField(blank=True)),
                ('cover_image', models.URLField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('categories', models.ManyToManyField(blank=True, related_name='organizations', to='locations.activitycategory')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organizations', to='locations.city')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_organizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'НКО',
                'verbose_name_plural': 'НКО',
                'ordering': ['name'],
            },
        ),
    ]
