# Generated by Django 4.2.10 on 2025-11-16 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='cover_file',
            field=models.FileField(blank=True, help_text='Может быть изображение или видео', null=True, upload_to='organizations/covers/'),
        ),
        migrations.AddField(
            model_name='organization',
            name='logo_file',
            field=models.ImageField(blank=True, null=True, upload_to='organizations/logos/'),
        ),
    ]
