# Generated by Django 4.2.10 on 2025-11-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='cover_file',
            field=models.FileField(blank=True, help_text='Может быть изображение или видео', null=True, upload_to='materials/covers/'),
        ),
    ]
