# Generated by Django 4.2.10 on 2025-11-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
